services:
  rest-service:
    container_name: rest-service
    build: ./services/rest-service
    env_file:
      - ./services/rest-service/.env
    ports:
      - "8001:8000"
    volumes:
      - ./services/rest-service:/app  
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongo

  # graphql-service:
  #   container_name: graphql-service
  #   build: ./services/graphql-service
  #   env_file:
  #     - ./services/graphql-service/.env
  #   ports:
  #     - "8002:8000"
  #   volumes:
  #     - ./services/graphql-service:/app  
  #   command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  #   depends_on:
  #     - mongo

  mongo:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: