services:



  # rest-service:
  #   container_name: rest-service
  
  #   build: ./services/rest-service

  #   env_file:
  #     - ./services/rest-service/.env

  #   ports:
  #     - "8001:8000"

  #   volumes:
  #     - ./services/rest-service:/app  

  #   command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  #   depends_on:
  #     - mongo



  # graphql-service:
  #   container_name: graphql-service

  #   build: ./services/graphql-service

  #   env_file:
  #     - ./services/graphql-service/.env

  #   ports:
  #     - "8002:8000"

  #   volumes:
  #     - ./services/graphql-service:/app  

  #   command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  #   depends_on:
  #     - mongo



  # grpc-service:
  #   container_name: grpc-service

  #   build:
  #     context: ./services/grpc-service

  #   env_file:
  #     - ./services/grpc-service/.env

  #   ports:
  #     - "8003:8080"

  #   depends_on:
  #     sqlserver:
  #       condition: service_healthy
      
  #   networks:
  #     - services-network



  # soap-service:
  #   container_name: soap-service

  #   build: 
  #     context: ./services/soap-service

  #   env_file:
  #     - ./services/soap-service/.env

  #   ports:
  #     - "8004:8080"

  #   depends_on:
  #     sqlserver:
  #       condition: service_healthy

  #   networks:
  #     - services-network


  # docker-compose.yml  (adicionar ao arquivo existente)

  rabbitmq-producer:
    container_name: rabbitmq-producer

    build: ./services/rabbitmq-service/producer

    env_file:
      - ./services/rabbitmq-service/producer/.env

    ports:
      - "8005:8000"

    volumes:
      - ./services/rabbitmq-service/producer:/app

    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    depends_on:
      rabbitmq:
        condition: service_healthy

    networks:
      - services-network

  rabbitmq-consumer:
    container_name: rabbitmq-consumer

    build:
      context: ./services/rabbitmq-service/consumer

    env_file:
      - ./services/rabbitmq-service/consumer/.env

    ports:
      - "8006:8080"

    depends_on:
      rabbitmq:
        condition: service_healthy
      sqlserver:
        condition: service_healthy

    networks:
      - services-network


  # rabbitmq-consumer:
  #   container_name: rabbitmq-consumer

  #   build:
  #     context: ./services/rabbitmq-service/consumer

  #   env_file:
  #     - ./services/rabbitmq-service/consumer/.env

  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     sqlserver:
  #       condition: service_healthy

  #   networks:
  #     - services-network


  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq

    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI  →  http://localhost:15672

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - services-network




  # mongo:
  #   image: mongo:7

  #   container_name: mongo_db

  #   ports:
  #     - "27017:27017"

  #   volumes:
  #     - mongo_data:/data/db

  #   restart: unless-stopped
    

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"

    ports:
      - "1433:1433"

    volumes:
      - sql_data:/var/opt/mssqlfrabbitmq

    healthcheck:
      test: 
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P 'YourStrong!Passw0rd' -Q 'SELECT 1' || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - services-network



volumes:
  # mongo_data:
  sql_data:
  rabbitmq_data:

networks:
  services-network:
    driver: bridge